Build and push the appliance disk images

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -30,6 +30,11 @@ REPO=${REPO:-docker.io/manageiq}
 
 CONTAINER_COMMAND="$(which podman &>/dev/null && echo "podman" || echo "docker")"
 
+if [[ -z "$NO_APPLIANCES" && -n "$PUSH" && -z "$IBM_CLOUD_API_KEY" ]]; then
+  echo "ERROR: Missing IBM_CLOUD_API_KEY"
+  exit 1
+fi
+
 set -e
 
 if [ -n "$REBUILD_RPM" ]; then
@@ -62,7 +67,7 @@ if [ -n "$RELEASE_BUILD" -a "$image" == "manageiq-base" ]; then
 fi
 
 pushd $IMAGE_DIR
-  # Pull the base image first
+  echo "Pulling base UBI image"
   $CONTAINER_COMMAND pull registry.access.redhat.com/ubi10/ubi
 
   build_images="manageiq-rpms manageiq-base manageiq-base-worker manageiq-orchestrator manageiq-webserver-worker manageiq-ui-worker"
@@ -84,28 +89,28 @@ fi
 
 appliance_images_to_push=""
 if [ -z "$NO_APPLIANCES" ]; then
+  echo "Pulling base appliance bootc image"
   $CONTAINER_COMMAND pull quay.io/centos-bootc/centos-bootc:stream10
   pushd images/manageiq-appliance
 
-  target_tag="$REPO/manageiq-appliance:$TAG"
-  cmd="$CONTAINER_BUILD_COMMAND . --tag $target_tag"
+  cmd="$CONTAINER_BUILD_COMMAND . --tag $REPO/manageiq-appliance-base:$TAG"
   echo "Building $image: $cmd"
   $cmd
 
   for containerfile in $(ls Containerfile.*); do
     target=${containerfile##*.}
 
-    target_tag="$REPO/manageiq-appliance:$TAG-$target"
-    cmd="$CONTAINER_BUILD_COMMAND . -f $containerfile --tag $target_tag"
+    cmd="$CONTAINER_BUILD_COMMAND . -f $containerfile --tag $REPO/manageiq-appliance-$target:$TAG"
     echo "Building $image: $cmd"
     $cmd
-    appliance_images_to_push+="$target_tag "
+    appliance_images_to_push+="manageiq-appliance-$target "
   done
   popd
 fi
 
 if [ -n "$PUSH" ]; then
   push_images="manageiq-base manageiq-base-worker manageiq-orchestrator manageiq-webserver-worker manageiq-ui-worker"
+  push_images+=" $appliance_images_to_push"
   if [ -z "$NO_OPERATOR" ]; then
     push_images="$push_images manageiq-operator"
   fi
@@ -121,18 +126,73 @@ if [ -n "$PUSH" ]; then
     echo "Pushing $image: $cmd"
     $cmd
   done
+fi
 
-  if [ -z "$NO_APPLIANCES" ]; then
-    for image in $appliance_images_to_push; do
-      cmd="$CONTAINER_COMMAND push $image"
+# Build the disk images
+if [ -z "$NO_APPLIANCES" ]; then
+  echo "Pulling bootc image builder image"
+  sudo podman pull quay.io/centos-bootc/bootc-image-builder:latest
 
-      # --format docker is needed for podman to ensure the builds are built with docker v2 manifests
-      if [ "$CONTAINER_COMMAND" == "podman" ]; then
-        cmd+=" --format docker"
+  for appliance_image in $appliance_images_to_push; do
+    echo "Building Appliance Disk for: $appliance_image"
+    target_platform="${appliance_image##*-}"
+    case "$target_platform" in
+      azure|ec2|hyperv|vagrant)
+        disk_type="vhd"
+        ;;
+      gce)
+        disk_type="gce"
+        ;;
+      vsphere)
+        disk_type="vmdk"
+        ;;
+      *)
+        # libvirt, openstack, ovirt
+        disk_type="qcow2"
+        ;;
+    esac
+
+    echo "Pulling appliance image: $REPO/$appliance_image:$TAG"
+    sudo podman pull "$REPO/$appliance_image:$TAG"
+
+    echo "Building appliance disk image"
+    sudo podman run \
+        --rm \
+        -it \
+        --privileged \
+        --security-opt label=type:unconfined_t \
+        -v ./images/manageiq-appliance/config.toml.$target_platform:/config.toml:ro \
+        -v ./output:/output \
+        -v /var/lib/containers/storage:/var/lib/containers/storage \
+        quay.io/centos-bootc/bootc-image-builder:latest \
+        --type $disk_type \
+        --use-librepo=True \
+        --chown $(id -u):$(id -g) \
+        "$REPO/$appliance_image:$TAG"
+
+    if [ -n "$PUSH" ]; then
+      if [ "$disk_type" == "vhd" ]; then
+        pushd output/vpc/
+          echo "Zipping VHD..."
+          zip -m -j disk.zip disk.vhd
+        popd
       fi
 
-      echo "Pushing $image: $cmd"
-      $cmd
-    done
-  fi
+      disk_image=$(find ./output/ -type f ! -name "*.json" ! -name ".gitkeep")
+      destination_name="$RPM_PREFIX-$target_platform-$TAG.$disk_type"
+
+      # Obtain bearer token
+      echo "Obtaining bearer token..."
+      response=$(curl --fail -s -X "POST" "https://iam.cloud.ibm.com/oidc/token" -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode "apikey=$IBM_CLOUD_API_KEY" --data-urlencode "response_type=cloud_iam" --data-urlencode "grant_type=urn:ibm:params:oauth:grant-type:apikey")
+      access_token=$(echo $response | jq -r ".access_token")
+
+      # Upload
+      echo
+      echo "Uploading..."
+      bucket="releases-manageiq-org"
+      curl -X "PUT" -H "Authorization: Bearer $access_token" -H "Content-Type: application/octet-stream" -H "x-amz-acl: public-read" -T "$disk_image" "https://s3.us-east.cloud-object-storage.appdomain.cloud/releases-manageiq-org/$destination_name"
+
+      rm -rf output/*
+    fi
+  done
 fi
