Merge pull request #960 from Fryguy/fix_hotfix
Fix various hotfix issues

(cherry picked from commit 9af45375985723b481f42e3c923cef0293b7b548)

diff --git a/bin/build_hotfix b/bin/build_hotfix
--- a/bin/build_hotfix
+++ b/bin/build_hotfix
@@ -20,6 +20,11 @@ while getopts "t:c:d:r:hblnops" opt; do
   esac
 done
 
+if [ -z "$FROM_TAG" ]; then
+  echo "ERROR: FROM_TAG is required for hotfixes"
+  exit 1
+fi
+
 BASE_DIR=${BASE_DIR:-$PWD}
 CONTAINER_PREFIX=${CONTAINER_PREFIX:-manageiq}
 IMAGE_DIR="$BASE_DIR/images"
@@ -33,8 +38,10 @@ set -e
 pushd $IMAGE_DIR
   cmd="$CONTAINER_COMMAND build"
 
-  hotfix_images="manageiq-base manageiq-base-worker manageiq-orchestrator manageiq-webserver-worker manageiq-ui-worker"
+  hotfix_images="manageiq-base-worker manageiq-orchestrator manageiq-webserver-worker manageiq-ui-worker"
   for image in $hotfix_images; do
+    fromImage="${image/#manageiq/$CONTAINER_PREFIX}"
+
     cmd="$CONTAINER_COMMAND build"
 
     if [ "$CONTAINER_COMMAND" == "podman" ]; then
@@ -42,9 +49,7 @@ pushd $IMAGE_DIR
     fi
 
     cmd+=" --tag $REPO/$image:$TAG \
-           --build-arg CONTAINER_PREFIX=$CONTAINER_PREFIX \
-           --build-arg FROM_REPO=$REPO \
-           --build-arg FROM_TAG=$TAG \
+           --build-arg FROM_IMAGE=$REPO/$fromImage:$FROM_TAG \
            --pull \
            manageiq-hotfix"
 
@@ -54,7 +59,7 @@ pushd $IMAGE_DIR
 popd
 
 if [ -n "$PUSH" ]; then
-  push_images="manageiq-base manageiq-base-worker manageiq-orchestrator manageiq-webserver-worker manageiq-ui-worker"
+  push_images="manageiq-base-worker manageiq-orchestrator manageiq-webserver-worker manageiq-ui-worker"
 
   for image in $push_images; do
     cmd="$CONTAINER_COMMAND push $REPO/$image:$TAG"
