Consolidate orchestrator startup scripts
Many of the functions used by the orchestrator entrypoint script
were only used by the orchestrator, but were defined in the
base image.

This commit moves the functions or the content of the functions
directly into the orchestrator entrypoint script and does the
same for scripts directly in the orchestrator image which were
unnecessarily split out.

This makes the orchestrator entrypoint more readable and maintainable

diff --git a/images/manageiq-orchestrator/container-assets/entrypoint b/images/manageiq-orchestrator/container-assets/entrypoint
--- a/images/manageiq-orchestrator/container-assets/entrypoint
+++ b/images/manageiq-orchestrator/container-assets/entrypoint
@@ -1,8 +1,66 @@
 #!/bin/bash
 
-check-dependent-services.sh
-appliance-initialize.sh
-
 [[ -s /etc/default/evm ]] && source /etc/default/evm
+
+function check_svc_status() {
+  local SVC_NAME=$1 SVC_PORT=$2
+
+  [[ $# -lt 2 ]] && echo "Error something seems wrong, we need at least two parameters to check service status" && exit 1
+
+  echo "== Checking ${SVC_NAME}:$SVC_PORT status =="
+
+  while true; do
+    ncat ${SVC_NAME} ${SVC_PORT} < /dev/null && break
+    sleep 5
+  done
+  echo "${SVC_NAME}:${SVC_PORT} - accepting connections"
+}
+
+check_svc_status ${MEMCACHED_SERVICE_HOST} ${MEMCACHED_SERVICE_PORT}
+check_svc_status ${POSTGRESQL_SERVICE_HOST} ${POSTGRESQL_SERVICE_PORT}
+
+echo "== Writing encryption key =="
+cat > /var/www/miq/vmdb/certs/v2_key << KEY
+---
+:algorithm: aes-256-cbc
+:key: ${V2_KEY}
+KEY
+
+echo "${GUID}" > ${APP_ROOT}/GUID
+
+set -e
+
+cd ${APP_ROOT}
+bin/rake evm:deployment_status
+case $? in
+  3) # new_deployment
+    echo "== Starting New Deployment =="
+
+    pushd ${APP_ROOT}
+      REGION=${DATABASE_REGION} bin/rake db:migrate
+      REGION=${DATABASE_REGION} bin/rails runner "MiqDatabase.seed; MiqRegion.seed"
+
+      echo "== Setting admin password =="
+      bin/rails runner "EvmDatabase.seed_primordial; user = User.lookup_by_userid('admin').update_attributes!(:password => ENV['APPLICATION_ADMIN_PASSWORD'])"
+    popd
+  ;;
+  4) # new_replica
+    echo "New replica is not supported, exiting.."
+    exit 1
+  ;;
+  5) # redeployment
+    echo "== Starting Re-deployment =="
+  ;;
+  6) # upgrade
+    echo "== Starting Upgrade =="
+    pushd ${APP_ROOT}
+      bin/rake db:migrate
+      [ "$?" -ne "0" ] && echo "ERROR: Failed to migrate database" && exit 1
+    popd
+  ;;
+  *)
+    echo "Could not find a suitable deployment type, exiting.."
+    exit 1
+esac
 
 exec ruby /var/www/miq/vmdb/lib/workers/bin/evm_server.rb
